### ISSUE TITLE
集成项目启动报错

### ISSUE THREAD

**Issue by chenxn527** [iyangyuan/pay-spring-boot#2]
GoodsTradeManager.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
GoodsTradeManager类无法启动注入，请问怎么处理？

**Comment by WolfyCoder** [comment]
> GoodsTradeManager.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
> GoodsTradeManager类无法启动注入，请问怎么处理？
怎么解决的？

**Comment by chenxn527** [comment]
保证你的支付宝账号是正确可用的，代码没问题。断点调试发现支付宝账号初始化失败------------------ 原始邮件 ------------------
发件人: "WolfyCoder"<notifications@github.com>
发送时间: 2019年8月3日(星期六) 上午8:36
收件人: "iyangyuan/pay-spring-boot"<pay-spring-boot@noreply.github.com>;
抄送: "chenxn527"<251145316@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [iyangyuan/pay-spring-boot] 集成项目启动报错 (#2)


 
GoodsTradeManager.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
 GoodsTradeManager类无法启动注入，请问怎么处理？
 怎么解决的？
  
&mdash;
